CREATE TABLE EMPLOYEE(EMPLOYEE_ID INT,EMPLOYEE_NAME VARCHAR(37),EMPLOYEE_SAL NUMBER(10));
DESC EMPLOYEE;

INSERT INTO EMPLOYEE VALUES(2,'YASH',20000);
INSERT INTO EMPLOYEE VALUES(9,'OMKAR',10000);
INSERT INTO EMPLOYEE VALUES(7,'RAJ',5000);
SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE ADD EMPLOYEE_DEPT VARCHAR(20);
SELECT * FROM EMPLOYEE;

DESC EMPLOYEE;
ALTER TABLE EMPLOYEE MODIFY EMPLOYEE_DEPT VARCHAR(29);
DESC EMPLOYEE;

CREATE TABLE EMPLO(EMPLO_ID INT,EMPLO_NAME VARCHAR(37),EMPLO_SAL NUMBER(10),CONSTRAINT EMPLO_PK PRIMARY KEY(EMPLO_ID));
DESC EMPLO;

UPDATE EMPLOYEE
 SET EMPLOYEE_DEPT=1
 WHERE EMPLOYEE_ID=2;
 SELECT * FROM EMPLOYEE;
 
 
 
 
 
 
 
 DESC EMPL;
 SELECT * FROM EMPL;
 
 SELECT * FROM EMPL WHERE EMP_JOB='SALESMAN' OR EMP_JOB='CLERK';
 
 SELECT * FROM EMPL WHERE EMP_NAME LIKE'S%';
 
 SELECT * FROM EMPL WHERE SAL BETWEEN 2000 AND 5000;
 
 SELECT * FROM EMPL WHERE EMP_NAME IN('BLAKE','KING','CLARK','SMITH');
 
 SELECT EMP_ID,EMP_NAME,SAL FROM EMPL WHERE MGR=7698;
 
 SELECT EMPLOYEE_ID,MAX(EMPLOYEE_SAL)FROM EMPLOYEE GROUP BY EMPLOYEE_ID;
 
 SELECT EMPLOYEE_ID,MIN(EMPLOYEE_SAL)FROM EMPLOYEE GROUP BY EMPLOYEE_ID;
 
 SELECT SUM(EMPLOYEE_SAL)FROM EMPLOYEE;
 
SELECT AVG(EMPLOYEE_SAL)FROM EMPLOYEE;
 
SELECT COUNT(*) FROM EMPLOYEE;

SELECT COUNT(ECOMM)FROM EMPL;

 SELECT EMP_NAME,MAX(SAL) FROM EMPL WHERE DEPT_NO=10 GROUP BY EMP_NAME;
 
 SELECT EMP_NAME,MAX(SAL) FROM EMPL WHERE DEPT_NO=20 GROUP BY EMP_NAME;
 
