CREATE TABLE EMP1(
EMPID INT,
ENAME VARCHAR(37)
);
DESC EMP1;
INSERT INTO EMP1 VALUES(1,'REENA');
INSERT INTO EMP1 VALUES(2,'SEEMA');
INSERT INTO EMP1 VALUES(3,'GEETA');
INSERT INTO EMP1 VALUES(7,'ROHIT');
INSERT INTO EMP1 VALUES(8,'ROHAN');
SELECT * FROM EMP1;


CREATE TABLE EMP2(
EMPID INT,
ENAME VARCHAR(37)
);
DESC EMP2;
INSERT INTO EMP2 VALUES(4,'AKASH');
INSERT INTO EMP2 VALUES(1,'REENA');
INSERT INTO EMP2 VALUES(2,'SEEMA');
INSERT INTO EMP2 VALUES(76,'GEETA');
SELECT * FROM EMP2;


SELECT * FROM EMP1 MINUS SELECT * FROM EMP2;
SELECT * FROM EMP1 UNION SELECT * FROM EMP2;
SELECT * FROM EMP1 INTERSECT SELECT * FROM EMP2;
SELECT * FROM EMP1 UNION ALL SELECT * FROM EMP2;
SELECT EMPID AS ID,ENAME AS FNAME FROM EMP1 ;